// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UIAdvancedSettings ← SettingsData.advanced
 */
export class UIAdvancedSettings {
    "allowWindowedMode": boolean;
    "experimentalFeatures": boolean;
    "webglRenderer": boolean;
    "debugMode": boolean;
    "scrollback": number;
    "nointro": boolean;
    "forceFullscreen": boolean;
    "hideDotfiles": boolean;
    "fsListView": boolean;
    "experimentalGlobeFeatures": boolean;

    /** Creates a new UIAdvancedSettings instance. */
    constructor($$source: Partial<UIAdvancedSettings> = {}) {
        if (!("allowWindowedMode" in $$source)) {
            this["allowWindowedMode"] = false;
        }
        if (!("experimentalFeatures" in $$source)) {
            this["experimentalFeatures"] = false;
        }
        if (!("webglRenderer" in $$source)) {
            this["webglRenderer"] = false;
        }
        if (!("debugMode" in $$source)) {
            this["debugMode"] = false;
        }
        if (!("scrollback" in $$source)) {
            this["scrollback"] = 0;
        }
        if (!("nointro" in $$source)) {
            this["nointro"] = false;
        }
        if (!("forceFullscreen" in $$source)) {
            this["forceFullscreen"] = false;
        }
        if (!("hideDotfiles" in $$source)) {
            this["hideDotfiles"] = false;
        }
        if (!("fsListView" in $$source)) {
            this["fsListView"] = false;
        }
        if (!("experimentalGlobeFeatures" in $$source)) {
            this["experimentalGlobeFeatures"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIAdvancedSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UIAdvancedSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UIAdvancedSettings($$parsedSource as Partial<UIAdvancedSettings>);
    }
}

/**
 * UIAudioSettings ← SettingsData.audio
 */
export class UIAudioSettings {
    "enabled": boolean;
    "volume": number;
    "soundpack": string;
    "muteInBackground": boolean;
    "boot": boolean;
    "shutdown": boolean;

    /**
     * Per-category opt-outs (keyboard / destructive / interface clicks).
     */
    "categoryKeyboard": boolean;
    "categoryDestructive": boolean;
    "categoryInterface": boolean;

    /** Creates a new UIAudioSettings instance. */
    constructor($$source: Partial<UIAudioSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("volume" in $$source)) {
            this["volume"] = 0;
        }
        if (!("soundpack" in $$source)) {
            this["soundpack"] = "";
        }
        if (!("muteInBackground" in $$source)) {
            this["muteInBackground"] = false;
        }
        if (!("boot" in $$source)) {
            this["boot"] = false;
        }
        if (!("shutdown" in $$source)) {
            this["shutdown"] = false;
        }
        if (!("categoryKeyboard" in $$source)) {
            this["categoryKeyboard"] = false;
        }
        if (!("categoryDestructive" in $$source)) {
            this["categoryDestructive"] = false;
        }
        if (!("categoryInterface" in $$source)) {
            this["categoryInterface"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIAudioSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UIAudioSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UIAudioSettings($$parsedSource as Partial<UIAudioSettings>);
    }
}

/**
 * UIDisplaySettings ← SettingsData.display
 */
export class UIDisplaySettings {
    "theme": string;
    "keyboardLayout": string;
    "terminalFontSize": number;
    "fontFamily": string;

    /**
     * Layout preset override. Empty = follow the active theme's layout.
     */
    "layout": string;

    /** Creates a new UIDisplaySettings instance. */
    constructor($$source: Partial<UIDisplaySettings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("keyboardLayout" in $$source)) {
            this["keyboardLayout"] = "";
        }
        if (!("terminalFontSize" in $$source)) {
            this["terminalFontSize"] = 0;
        }
        if (!("fontFamily" in $$source)) {
            this["fontFamily"] = "";
        }
        if (!("layout" in $$source)) {
            this["layout"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIDisplaySettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UIDisplaySettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UIDisplaySettings($$parsedSource as Partial<UIDisplaySettings>);
    }
}

/**
 * UINetworkSettings ← SettingsData.network
 */
export class UINetworkSettings {
    "pingTarget": string;
    "adapter": string;
    "pingIntervalMs": number;
    "trafficIntervalMs": number;
    "geoipEnabled": boolean;
    "geoipEndpoint": string;

    /** Creates a new UINetworkSettings instance. */
    constructor($$source: Partial<UINetworkSettings> = {}) {
        if (!("pingTarget" in $$source)) {
            this["pingTarget"] = "";
        }
        if (!("adapter" in $$source)) {
            this["adapter"] = "";
        }
        if (!("pingIntervalMs" in $$source)) {
            this["pingIntervalMs"] = 0;
        }
        if (!("trafficIntervalMs" in $$source)) {
            this["trafficIntervalMs"] = 0;
        }
        if (!("geoipEnabled" in $$source)) {
            this["geoipEnabled"] = false;
        }
        if (!("geoipEndpoint" in $$source)) {
            this["geoipEndpoint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UINetworkSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UINetworkSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UINetworkSettings($$parsedSource as Partial<UINetworkSettings>);
    }
}

/**
 * UISettings is the typed, file-persisted mirror of the frontend's
 * `adex-settings` object (the SettingsData interface in
 * AdexSettingsModal.vue). It is DELIBERATELY separate from AppSettings:
 * 
 *   - AppSettings is the legacy eDEX-shaped 477-line config consumed by
 *     the font / system / theme Go services with their own field
 *     expectations. Cramming the lean frontend shape into it would
 *     force changes across those consumers.
 *   - UISettings instead matches the frontend SettingsData 1:1, field
 *     for field, so the round-trip is a plain JSON marshal/unmarshal
 *     with no lossy mapping layer.
 * 
 * Persistence model: this struct is the SOURCE OF TRUTH (a real file
 * under the user config dir, atomic write + .bak backup). The
 * frontend's localStorage is only a fast reactive cache that is
 * seeded from here on boot and flushed back here (debounced) on
 * change. Backend always wins on a boot conflict.
 * 
 * When the frontend adds a setting, add the matching field here too
 * (the user chose typed reconciliation over an opaque blob precisely
 * so the Go side stays a checkable contract).
 * 
 * This is a plain value DTO — no embedded mutex. Concurrency is the
 * owning store's responsibility (settings.UIStore), so the struct
 * stays freely copyable for safe snapshot returns.
 */
export class UISettings {
    /**
     * Metadata — not part of the frontend shape; we stamp these on
     * save so the file is self-describing and migrations can branch
     * on Version later.
     */
    "version": string;
    "updatedAt": string;
    "shell": UIShellSettings;
    "display": UIDisplaySettings;
    "audio": UIAudioSettings;
    "system": UISystemSettings;
    "network": UINetworkSettings;
    "advanced": UIAdvancedSettings;

    /** Creates a new UISettings instance. */
    constructor($$source: Partial<UISettings> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("shell" in $$source)) {
            this["shell"] = (new UIShellSettings());
        }
        if (!("display" in $$source)) {
            this["display"] = (new UIDisplaySettings());
        }
        if (!("audio" in $$source)) {
            this["audio"] = (new UIAudioSettings());
        }
        if (!("system" in $$source)) {
            this["system"] = (new UISystemSettings());
        }
        if (!("network" in $$source)) {
            this["network"] = (new UINetworkSettings());
        }
        if (!("advanced" in $$source)) {
            this["advanced"] = (new UIAdvancedSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UISettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UISettings {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shell" in $$parsedSource) {
            $$parsedSource["shell"] = $$createField2_0($$parsedSource["shell"]);
        }
        if ("display" in $$parsedSource) {
            $$parsedSource["display"] = $$createField3_0($$parsedSource["display"]);
        }
        if ("audio" in $$parsedSource) {
            $$parsedSource["audio"] = $$createField4_0($$parsedSource["audio"]);
        }
        if ("system" in $$parsedSource) {
            $$parsedSource["system"] = $$createField5_0($$parsedSource["system"]);
        }
        if ("network" in $$parsedSource) {
            $$parsedSource["network"] = $$createField6_0($$parsedSource["network"]);
        }
        if ("advanced" in $$parsedSource) {
            $$parsedSource["advanced"] = $$createField7_0($$parsedSource["advanced"]);
        }
        return new UISettings($$parsedSource as Partial<UISettings>);
    }
}

/**
 * UIShellSettings ← SettingsData.shell
 */
export class UIShellSettings {
    "path": string;
    "args": string;
    "workingDirectory": string;

    /** Creates a new UIShellSettings instance. */
    constructor($$source: Partial<UIShellSettings> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }
        if (!("workingDirectory" in $$source)) {
            this["workingDirectory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIShellSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UIShellSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UIShellSettings($$parsedSource as Partial<UIShellSettings>);
    }
}

/**
 * UISystemSettings ← SettingsData.system
 */
export class UISystemSettings {
    /**
     * "home" or "cwd" — where new shells / file manager open.
     */
    "initialCwd": string;

    /**
     * "12h" or "24h".
     */
    "clockFormat": string;
    "bootAnimation": boolean;
    "gridBackground": boolean;
    "performanceMode": boolean;

    /** Creates a new UISystemSettings instance. */
    constructor($$source: Partial<UISystemSettings> = {}) {
        if (!("initialCwd" in $$source)) {
            this["initialCwd"] = "";
        }
        if (!("clockFormat" in $$source)) {
            this["clockFormat"] = "";
        }
        if (!("bootAnimation" in $$source)) {
            this["bootAnimation"] = false;
        }
        if (!("gridBackground" in $$source)) {
            this["gridBackground"] = false;
        }
        if (!("performanceMode" in $$source)) {
            this["performanceMode"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UISystemSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UISystemSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UISystemSettings($$parsedSource as Partial<UISystemSettings>);
    }
}

// Private type creation functions
const $$createType0 = UIShellSettings.createFrom;
const $$createType1 = UIDisplaySettings.createFrom;
const $$createType2 = UIAudioSettings.createFrom;
const $$createType3 = UISystemSettings.createFrom;
const $$createType4 = UINetworkSettings.createFrom;
const $$createType5 = UIAdvancedSettings.createFrom;
