// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UIAdvancedSettings ← SettingsData.advanced
 */
export interface UIAdvancedSettings {
    "allowWindowedMode": boolean;
    "experimentalFeatures": boolean;
    "webglRenderer": boolean;
    "debugMode": boolean;
    "scrollback": number;
    "nointro": boolean;
    "forceFullscreen": boolean;
    "hideDotfiles": boolean;
    "fsListView": boolean;
    "experimentalGlobeFeatures": boolean;
}

/**
 * UIAudioSettings ← SettingsData.audio
 */
export interface UIAudioSettings {
    "enabled": boolean;
    "volume": number;
    "soundpack": string;
    "muteInBackground": boolean;
    "boot": boolean;
    "shutdown": boolean;

    /**
     * Per-category opt-outs (keyboard / destructive / interface clicks).
     */
    "categoryKeyboard": boolean;
    "categoryDestructive": boolean;
    "categoryInterface": boolean;
}

/**
 * UIDisplaySettings ← SettingsData.display
 */
export interface UIDisplaySettings {
    "theme": string;
    "keyboardLayout": string;
    "terminalFontSize": number;
    "fontFamily": string;

    /**
     * Layout preset override. Empty = follow the active theme's layout.
     */
    "layout": string;
}

/**
 * UINetworkSettings ← SettingsData.network
 */
export interface UINetworkSettings {
    "pingTarget": string;
    "adapter": string;
    "pingIntervalMs": number;
    "trafficIntervalMs": number;
    "geoipEnabled": boolean;
    "geoipEndpoint": string;
}

/**
 * UISettings is the typed, file-persisted mirror of the frontend's
 * `adex-settings` object (the SettingsData interface in
 * AdexSettingsModal.vue). It is DELIBERATELY separate from AppSettings:
 * 
 *   - AppSettings is the legacy eDEX-shaped 477-line config consumed by
 *     the font / system / theme Go services with their own field
 *     expectations. Cramming the lean frontend shape into it would
 *     force changes across those consumers.
 *   - UISettings instead matches the frontend SettingsData 1:1, field
 *     for field, so the round-trip is a plain JSON marshal/unmarshal
 *     with no lossy mapping layer.
 * 
 * Persistence model: this struct is the SOURCE OF TRUTH (a real file
 * under the user config dir, atomic write + .bak backup). The
 * frontend's localStorage is only a fast reactive cache that is
 * seeded from here on boot and flushed back here (debounced) on
 * change. Backend always wins on a boot conflict.
 * 
 * When the frontend adds a setting, add the matching field here too
 * (the user chose typed reconciliation over an opaque blob precisely
 * so the Go side stays a checkable contract).
 * 
 * This is a plain value DTO — no embedded mutex. Concurrency is the
 * owning store's responsibility (settings.UIStore), so the struct
 * stays freely copyable for safe snapshot returns.
 */
export interface UISettings {
    /**
     * Metadata — not part of the frontend shape; we stamp these on
     * save so the file is self-describing and migrations can branch
     * on Version later.
     */
    "version": string;
    "updatedAt": string;
    "shell": UIShellSettings;
    "display": UIDisplaySettings;
    "audio": UIAudioSettings;
    "system": UISystemSettings;
    "network": UINetworkSettings;
    "advanced": UIAdvancedSettings;
}

/**
 * UIShellSettings ← SettingsData.shell
 */
export interface UIShellSettings {
    "path": string;
    "args": string;
    "workingDirectory": string;
}

/**
 * UISystemSettings ← SettingsData.system
 */
export interface UISystemSettings {
    /**
     * "home" or "cwd" — where new shells / file manager open.
     */
    "initialCwd": string;

    /**
     * "12h" or "24h".
     */
    "clockFormat": string;
    "bootAnimation": boolean;
    "gridBackground": boolean;
    "performanceMode": boolean;
}
