// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StartupPaths returns the directories the frontend can offer the user as
 * "open in this directory on launch" choices.
 * 
 * 	{ "home": "/home/ano", "cwd": "/var/www/aDex-UI" }
 * 
 * Driven by a new initial-cwd setting in the Settings modal so the
 * terminal + file manager respect a user-chosen default.
 */
export interface StartupPaths {
    "home": string;
    "cwd": string;
}
