// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * StartupPaths returns the directories the frontend can offer the user as
 * "open in this directory on launch" choices.
 * 
 * 	{ "home": "/home/ano", "cwd": "/var/www/aDex-UI" }
 * 
 * Driven by a new initial-cwd setting in the Settings modal so the
 * terminal + file manager respect a user-chosen default.
 */
export class StartupPaths {
    "home": string;
    "cwd": string;

    /** Creates a new StartupPaths instance. */
    constructor($$source: Partial<StartupPaths> = {}) {
        if (!("home" in $$source)) {
            this["home"] = "";
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartupPaths instance from a string or object.
     */
    static createFrom($$source: any = {}): StartupPaths {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartupPaths($$parsedSource as Partial<StartupPaths>);
    }
}
