// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServiceCoordinator manages all application services
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminal$0 from "../terminal/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as utils$0 from "../../utils/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../../../internal/events/models.js";

/**
 * CloseTerminal closes a terminal session
 */
export function CloseTerminal(terminalID: string): $CancellablePromise<void> {
    return $Call.ByID(2919091542, terminalID);
}

/**
 * CreateTerminal creates a new terminal session
 */
export function CreateTerminal(width: number, height: number): $CancellablePromise<terminal$0.Terminal | null> {
    return $Call.ByID(2670237022, width, height).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetEventBus returns the event bus
 */
export function GetEventBus(): $CancellablePromise<events$0.EventBus | null> {
    return $Call.ByID(3784317956).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetPlatform returns platform information
 */
export function GetPlatform(): $CancellablePromise<utils$0.FeatureDetection | null> {
    return $Call.ByID(1459214277).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetService returns a service by type (interface{})
 */
export function GetService(serviceType: string): $CancellablePromise<any> {
    return $Call.ByID(2120592893, serviceType);
}

/**
 * GetTerminalInfo returns information about a terminal session
 */
export function GetTerminalInfo(terminalID: string): $CancellablePromise<terminal$0.Terminal | null> {
    return $Call.ByID(317199030, terminalID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Initialize initializes all services
 */
export function Initialize(): $CancellablePromise<void> {
    return $Call.ByID(3410051216);
}

/**
 * IsStarted returns whether the coordinator is started
 */
export function IsStarted(): $CancellablePromise<boolean> {
    return $Call.ByID(612146383);
}

/**
 * ListTerminals returns all active terminal sessions
 */
export function ListTerminals(): $CancellablePromise<string[]> {
    return $Call.ByID(1956517423).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ResizeTerminal resizes a terminal session
 */
export function ResizeTerminal(terminalID: string, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(3068103278, terminalID, width, height);
}

/**
 * Shutdown gracefully shuts down all services
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(881873356);
}

/**
 * StartMonitoring starts monitoring for all services that support it
 */
export function StartMonitoring(): $CancellablePromise<void> {
    return $Call.ByID(1362246788);
}

/**
 * StopMonitoring stops monitoring for all services
 */
export function StopMonitoring(): $CancellablePromise<void> {
    return $Call.ByID(853345988);
}

/**
 * WriteToTerminal writes data to a terminal session
 */
export function WriteToTerminal(terminalID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(1503072468, terminalID, data);
}

// Private type creation functions
const $$createType0 = terminal$0.Terminal.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = events$0.EventBus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = utils$0.FeatureDetection.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
