// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServiceCoordinator manages all application services
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminal$0 from "../terminal/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as utils$0 from "../../utils/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../../internal/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearNetworkAlerts clears all resolved network alerts
 */
export function ClearNetworkAlerts(): $CancellablePromise<void> {
    return $Call.ByID(2117985540);
}

/**
 * CloseTerminal closes a terminal session
 */
export function CloseTerminal(terminalID: string): $CancellablePromise<void> {
    return $Call.ByID(2919091542, terminalID);
}

/**
 * CopyFile copies src to dst.
 */
export function CopyFile(src: string, dst: string): $CancellablePromise<void> {
    return $Call.ByID(1207305321, src, dst);
}

/**
 * CreateColorScheme creates a new color scheme
 */
export function CreateColorScheme(scheme: any): $CancellablePromise<void> {
    return $Call.ByID(2308528662, scheme);
}

/**
 * CreateDirectory creates a new directory at path with mode 0o755.
 * Used by the file-manager "New Folder" action.
 */
export function CreateDirectory(path: string): $CancellablePromise<void> {
    return $Call.ByID(3968851877, path);
}

/**
 * CreateFile creates an empty file at path.
 * Used by the file-manager "New File" action.
 */
export function CreateFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(4220371544, path);
}

/**
 * CreateFontConfiguration creates a new font configuration
 */
export function CreateFontConfiguration(config: any): $CancellablePromise<void> {
    return $Call.ByID(1786455135, config);
}

/**
 * CreateTerminal creates a new terminal session in the user's home
 * directory. Kept for backwards compatibility with frontend code that
 * pre-dates the Settings → System "Open in" preference.
 */
export function CreateTerminal(width: number, height: number): $CancellablePromise<terminal$0.Terminal | null> {
    return $Call.ByID(2670237022, width, height).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateTerminalIn creates a new terminal session whose shell starts in
 * the supplied working directory. Empty `cwd` falls back to home (matches
 * the legacy CreateTerminal behavior).
 */
export function CreateTerminalIn(width: number, height: number, cwd: string): $CancellablePromise<terminal$0.Terminal | null> {
    return $Call.ByID(1491097665, width, height, cwd).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteColorScheme deletes a color scheme
 */
export function DeleteColorScheme(id: string): $CancellablePromise<void> {
    return $Call.ByID(3045576591, id);
}

/**
 * DeleteFile permanently removes a file or empty directory.
 * The frontend MUST confirm with the user before calling this.
 */
export function DeleteFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(3422944787, path);
}

/**
 * DeleteFontConfiguration deletes a font configuration
 */
export function DeleteFontConfiguration(id: string): $CancellablePromise<void> {
    return $Call.ByID(4195883314, id);
}

/**
 * GetActiveShell returns the shell executable path the resolver would
 * pick *right now* (override → $SHELL/$ComSpec → platform default).
 * Lets the frontend status bar display the honest shell path instead
 * of guessing '/bin/bash'.
 */
export function GetActiveShell(): $CancellablePromise<string> {
    return $Call.ByID(3841544962);
}

/**
 * GetBandwidthData returns bandwidth data for a specific interface
 */
export function GetBandwidthData(interfaceName: string): $CancellablePromise<any> {
    return $Call.ByID(734613951, interfaceName);
}

/**
 * GetCPUUsage returns current CPU usage with per-core data
 */
export function GetCPUUsage(): $CancellablePromise<any> {
    return $Call.ByID(1581681679);
}

/**
 * GetCWDStats returns aggregate CWD-tracking stats across all terminals.
 * Replaces the previous HTTP endpoint at /api/terminal/cwd/stats.
 */
export function GetCWDStats(): $CancellablePromise<terminal$0.CWDStats> {
    return $Call.ByID(3064388575).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetColorScheme returns a specific color scheme by ID
 */
export function GetColorScheme(id: string): $CancellablePromise<any> {
    return $Call.ByID(1495188030, id);
}

/**
 * GetColorSchemeConfig returns the color scheme configuration
 */
export function GetColorSchemeConfig(): $CancellablePromise<any> {
    return $Call.ByID(3881872840);
}

/**
 * GetColorSchemePreview generates a preview for a color scheme
 */
export function GetColorSchemePreview(id: string): $CancellablePromise<any> {
    return $Call.ByID(4063754130, id);
}

/**
 * GetColorSchemes returns all available color schemes
 */
export function GetColorSchemes(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2557206327).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetDefaultColorScheme returns the default color scheme
 */
export function GetDefaultColorScheme(): $CancellablePromise<any> {
    return $Call.ByID(923900393);
}

/**
 * GetDefaultFontConfiguration returns the default font configuration
 */
export function GetDefaultFontConfiguration(): $CancellablePromise<any> {
    return $Call.ByID(1887433904);
}

/**
 * GetDiskUsage returns disk usage information for all partitions
 */
export function GetDiskUsage(): $CancellablePromise<any> {
    return $Call.ByID(3982652914);
}

/**
 * GetFileInfo returns metadata for a single path.
 * Used by the file-manager Properties / Info modal.
 */
export function GetFileInfo(path: string): $CancellablePromise<any> {
    return $Call.ByID(2359168028, path);
}

/**
 * GetFontConfiguration returns a specific font configuration by ID
 */
export function GetFontConfiguration(id: string): $CancellablePromise<any> {
    return $Call.ByID(934207351, id);
}

/**
 * GetFontConfigurations returns all font configurations
 */
export function GetFontConfigurations(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2890470220).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetFontMetrics returns metrics for a font
 */
export function GetFontMetrics(family: string, size: number): $CancellablePromise<any> {
    return $Call.ByID(2550489256, family, size);
}

/**
 * GetFontSettings returns current font settings
 */
export function GetFontSettings(): $CancellablePromise<any> {
    return $Call.ByID(691116794);
}

/**
 * GetMemoryUsage returns current memory usage information
 */
export function GetMemoryUsage(): $CancellablePromise<any> {
    return $Call.ByID(3612724932);
}

/**
 * GetMonospaceFonts returns monospace fonts suitable for terminal use
 */
export function GetMonospaceFonts(): $CancellablePromise<any[]> {
    return $Call.ByID(1824599733).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetNetworkAlerts returns current network alerts
 */
export function GetNetworkAlerts(): $CancellablePromise<any> {
    return $Call.ByID(3298438499);
}

/**
 * GetNetworkConfig returns the current network service configuration
 */
export function GetNetworkConfig(): $CancellablePromise<any> {
    return $Call.ByID(4140070562);
}

/**
 * GetNetworkConnections returns current network connections
 */
export function GetNetworkConnections(): $CancellablePromise<any> {
    return $Call.ByID(3471189381);
}

/**
 * GetNetworkInfo returns network interface information
 */
export function GetNetworkInfo(): $CancellablePromise<any> {
    return $Call.ByID(2163428856);
}

/**
 * GetNetworkMetrics returns current network metrics
 */
export function GetNetworkMetrics(): $CancellablePromise<any> {
    return $Call.ByID(972147689);
}

/**
 * GetNetworkStatistics returns comprehensive network statistics
 */
export function GetNetworkStatistics(): $CancellablePromise<any> {
    return $Call.ByID(3928878455);
}

/**
 * GetPlatform returns platform information
 */
export function GetPlatform(): $CancellablePromise<utils$0.FeatureDetection | null> {
    return $Call.ByID(1459214277).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetPowerInfo returns the current power source + battery percent
 * using distatus/battery (cross-platform). The frontend SystemInfo
 * panel polls this so POWER reflects "AC" vs "Battery" in real time
 * — earlier the frontend hardcoded "AC Power".
 */
export function GetPowerInfo(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(4028720851).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSelfGeoIP returns the geolocation for the current public IP.
 * 
 * Two-provider strategy with automatic failover:
 * 
 *  1. PRIMARY: geo.kamero.ai — free, open source, no API key, no
 *     hard rate limit, sub-50ms via Vercel Edge. One round trip.
 *  2. FALLBACK: ipify (just the IP) → iplocate (geo for that IP).
 *     Two round trips but bulletproof — both providers are widely
 *     used and have generous free tiers.
 * 
 * Both paths are tried before giving up; we cache the answer for 30
 * minutes since public-IP geolocation rarely changes mid-session.
 * Returns an empty map (not error) on total failure so the UI shows
 * "Resolving..." and retries on the next poll cycle.
 */
export function GetSelfGeoIP(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1927000148).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetStartupPaths exposes the launch CWD and the user's home directory so
 * the frontend can route the terminal + file manager to whichever the
 * user picked in Settings → System → "Open in".
 */
export function GetStartupPaths(): $CancellablePromise<$models.StartupPaths> {
    return $Call.ByID(1425163917).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetSystemFonts returns all detected system fonts
 */
export function GetSystemFonts(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3265143207).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSystemInfo returns comprehensive system information
 */
export function GetSystemInfo(): $CancellablePromise<any> {
    return $Call.ByID(106342595);
}

/**
 * GetTemperatures returns hardware temperature sensors. Wraps the
 * system service so the frontend's network-status / hardware mods can
 * pull `{name, temperature, high, critical}` rows for display.
 * Returns an empty array (not error) when sensors are unavailable.
 */
export function GetTemperatures(): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(4270093341).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetTerminalCWD returns the live current working directory of the shell
 * process backing the given terminal. Replaces the previous HTTP endpoint at
 * /api/terminal/session/:sessionId/cwd with a direct Wails binding.
 */
export function GetTerminalCWD(terminalID: string): $CancellablePromise<string> {
    return $Call.ByID(642904692, terminalID);
}

/**
 * GetTerminalInfo returns information about a terminal session
 */
export function GetTerminalInfo(terminalID: string): $CancellablePromise<terminal$0.Terminal | null> {
    return $Call.ByID(317199030, terminalID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTopProcesses returns top processes by CPU or memory usage
 */
export function GetTopProcesses(metric: string, limit: number): $CancellablePromise<any> {
    return $Call.ByID(2139204086, metric, limit);
}

/**
 * GetUISettings returns the file-persisted frontend settings
 * (the `adex-settings` shape). The frontend calls this once on boot
 * to hydrate its localStorage cache; the backend file is the source
 * of truth, so on a conflict this value wins. Returns the typed
 * *models.UISettings so the Wails-generated TS binding stays a
 * checkable contract rather than an opaque blob.
 */
export function GetUISettings(): $CancellablePromise<models$0.UISettings | null> {
    return $Call.ByID(3302846093).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ImportFont imports a font from a file or URL
 */
export function ImportFont(request: any): $CancellablePromise<any> {
    return $Call.ByID(2576930878, request);
}

/**
 * Initialize initializes all services
 */
export function Initialize(): $CancellablePromise<void> {
    return $Call.ByID(3410051216);
}

/**
 * IsNetworkMonitoring returns whether network monitoring is currently active
 */
export function IsNetworkMonitoring(): $CancellablePromise<boolean> {
    return $Call.ByID(2413087822);
}

/**
 * IsStarted returns whether the coordinator is started
 */
export function IsStarted(): $CancellablePromise<boolean> {
    return $Call.ByID(612146383);
}

/**
 * ListTerminals returns all active terminal sessions
 */
export function ListTerminals(): $CancellablePromise<string[]> {
    return $Call.ByID(1956517423).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * MeasureLatency does a TCP round-trip to the supplied host:port and
 * returns elapsed milliseconds. Empty target → 8.8.8.8:53 (Google DNS).
 * Returns -1 on failure rather than erroring so the UI shows "N/A"
 * instead of an error toast.
 * 
 * Frontend exposes this with two preset choices (8.8.8.8:53 and
 * 1.1.1.1:53) plus a free-text override in Settings → Network. Picking
 * TCP-DNS instead of ICMP avoids the CAP_NET_RAW / setuid dance that
 * breaks ping on sandboxed builds (Snap/Flatpak/macOS app store).
 */
export function MeasureLatency(target: string): $CancellablePromise<number> {
    return $Call.ByID(2508787900, target);
}

/**
 * MoveFile moves/renames a file from src to dst (used for both rename and
 * move-to-trash flows).
 */
export function MoveFile(src: string, dst: string): $CancellablePromise<void> {
    return $Call.ByID(3449904665, src, dst);
}

/**
 * ReadDirectory reads the contents of a directory
 */
export function ReadDirectory(path: string): $CancellablePromise<any> {
    return $Call.ByID(1886204657, path);
}

/**
 * ResetNetworkService resets the network service
 */
export function ResetNetworkService(): $CancellablePromise<void> {
    return $Call.ByID(459684076);
}

/**
 * ResizeTerminal resizes a terminal session
 */
export function ResizeTerminal(terminalID: string, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(3068103278, terminalID, width, height);
}

/**
 * ResolveNetworkAlert resolves a network alert
 */
export function ResolveNetworkAlert(alertID: string): $CancellablePromise<void> {
    return $Call.ByID(2277829046, alertID);
}

/**
 * SaveUISettings persists the frontend's settings object. The
 * frontend sends the `adex-settings` value verbatim as a JSON string
 * (debounced on every change), and this writes it atomically to the
 * source-of-truth file. Taking a raw string rather than interface{}
 * avoids a lossy map round-trip and lets the store unmarshal onto a
 * defaults base so a partial / older-shaped payload still persists
 * completely.
 */
export function SaveUISettings(payload: string): $CancellablePromise<void> {
    return $Call.ByID(98764608, payload);
}

/**
 * ScanSystemFonts scans the system for available fonts
 */
export function ScanSystemFonts(): $CancellablePromise<void> {
    return $Call.ByID(4264580036);
}

/**
 * SetDefaultColorScheme sets the default color scheme
 */
export function SetDefaultColorScheme(id: string): $CancellablePromise<void> {
    return $Call.ByID(1254262477, id);
}

/**
 * SetDefaultFontConfiguration sets the default font configuration
 */
export function SetDefaultFontConfiguration(id: string): $CancellablePromise<void> {
    return $Call.ByID(3127102612, id);
}

/**
 * SetShellCommand stores a user-supplied shell-path override for new
 * terminals. Empty string clears the override and falls back to the
 * $SHELL / $ComSpec / platform-default chain. Called from
 * Settings → Terminal → "Shell Path".
 */
export function SetShellCommand(shell: string): $CancellablePromise<void> {
    return $Call.ByID(1989979765, shell);
}

/**
 * Shutdown gracefully shuts down all services
 * Shutdown gracefully tears every service down. Called from Wails's
 * OnShutdown. Order matters:
 * 
 *  1. Publish the shutdown event so subscribers can clean up.
 *  2. Stop monitoring loops (StopMonitoring is idempotent).
 *  3. Shutdown the audio service so its CGO PCM writer goroutine winds down
 *     (without this, `go test` hangs at process exit on Linux ALSA).
 *  4. Cancel the coordinator's context so any context-bound goroutines
 *     return.
 *  5. Close per-service resources.
 *  6. Drain the event bus and wait for delivery goroutines to exit.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(881873356);
}

/**
 * SignalProcess sends the given signal name (e.g. "SIGTERM", "SIGKILL")
 * to the process at pid. Driven by the process-table context menu.
 * 
 * We accept the signal as a string instead of an int so the Wails JSON
 * boundary stays stable and platform-neutral; the system service maps
 * the name onto a syscall.Signal internally.
 */
export function SignalProcess(pid: number, signal: string): $CancellablePromise<void> {
    return $Call.ByID(3092416951, pid, signal);
}

/**
 * StartMonitoring starts monitoring for all services that support it
 */
export function StartMonitoring(): $CancellablePromise<void> {
    return $Call.ByID(1362246788);
}

/**
 * StartNetworkMonitoring starts network monitoring
 */
export function StartNetworkMonitoring(): $CancellablePromise<void> {
    return $Call.ByID(653774186);
}

/**
 * StopMonitoring stops monitoring for all services
 */
export function StopMonitoring(): $CancellablePromise<void> {
    return $Call.ByID(853345988);
}

/**
 * StopNetworkMonitoring stops network monitoring
 */
export function StopNetworkMonitoring(): $CancellablePromise<void> {
    return $Call.ByID(1240415658);
}

/**
 * UpdateColorScheme updates an existing color scheme
 */
export function UpdateColorScheme(scheme: any): $CancellablePromise<void> {
    return $Call.ByID(3076922913, scheme);
}

/**
 * UpdateColorSchemeConfig updates the color scheme configuration
 */
export function UpdateColorSchemeConfig(config: any): $CancellablePromise<void> {
    return $Call.ByID(2608350723, config);
}

/**
 * UpdateFontConfiguration updates an existing font configuration
 */
export function UpdateFontConfiguration(config: any): $CancellablePromise<void> {
    return $Call.ByID(2242746168, config);
}

/**
 * UpdateFontSettings updates font settings
 */
export function UpdateFontSettings(settings: any): $CancellablePromise<void> {
    return $Call.ByID(31984975, settings);
}

/**
 * UpdateNetworkConfig updates the network service configuration
 */
export function UpdateNetworkConfig(config: any): $CancellablePromise<void> {
    return $Call.ByID(255205561, config);
}

/**
 * ValidateColorScheme validates a color scheme
 */
export function ValidateColorScheme(scheme: any): $CancellablePromise<any> {
    return $Call.ByID(1340016912, scheme);
}

/**
 * ValidateFont validates a font configuration
 */
export function ValidateFont(config: any): $CancellablePromise<any> {
    return $Call.ByID(692200433, config);
}

/**
 * WriteToTerminal writes data to a terminal session.
 * 
 * Frontend-facing signature is `string` (not `[]byte`) because Wails
 * bind marshals JS strings transparently for Go `string` params, while
 * Go `[]byte` params expect a base64-encoded JSON string. Mixing those
 * caused every keystroke to be re-decoded as base64 → garbage bytes
 * → garbage echo. Keeping the wire type as string and converting
 * internally is simpler and round-trips control codes (ESC, Ctrl-C,
 * arrow-key escape sequences) correctly because xterm.js sends them
 * as raw byte strings in the same encoding the PTY expects.
 */
export function WriteToTerminal(terminalID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(1503072468, terminalID, data);
}

// Private type creation functions
const $$createType0 = terminal$0.Terminal.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = terminal$0.CWDStats.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = utils$0.FeatureDetection.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.StartupPaths.createFrom;
const $$createType8 = $Create.Array($$createType3);
const $$createType9 = models$0.UISettings.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($Create.Any);
