// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CWDSession is a single session's last-known CWD.
 */
export class CWDSession {
    "cwd": string;
    "updatedAt": number;

    /** Creates a new CWDSession instance. */
    constructor($$source: Partial<CWDSession> = {}) {
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CWDSession instance from a string or object.
     */
    static createFrom($$source: any = {}): CWDSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CWDSession($$parsedSource as Partial<CWDSession>);
    }
}

/**
 * CWDStats summarizes per-session CWD-tracking state for the frontend.
 * Mirrors the legacy /api/terminal/cwd/stats response shape so existing
 * clients can adopt the new binding without reshaping.
 */
export class CWDStats {
    "enabled": boolean;
    "platform": string;
    "sessions": number;
    "resolutions": number;
    "lastResolvedAt": number;
    "strategy": string;
    "perSession": { [_ in string]?: CWDSession };

    /** Creates a new CWDStats instance. */
    constructor($$source: Partial<CWDStats> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("sessions" in $$source)) {
            this["sessions"] = 0;
        }
        if (!("resolutions" in $$source)) {
            this["resolutions"] = 0;
        }
        if (!("lastResolvedAt" in $$source)) {
            this["lastResolvedAt"] = 0;
        }
        if (!("strategy" in $$source)) {
            this["strategy"] = "";
        }
        if (!("perSession" in $$source)) {
            this["perSession"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CWDStats instance from a string or object.
     */
    static createFrom($$source: any = {}): CWDStats {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("perSession" in $$parsedSource) {
            $$parsedSource["perSession"] = $$createField6_0($$parsedSource["perSession"]);
        }
        return new CWDStats($$parsedSource as Partial<CWDStats>);
    }
}

/**
 * Terminal represents a terminal session.
 * 
 * JSON tags are critical: this struct is returned by Wails-bound methods
 * (`CreateTerminal`, `GetTerminalInfo`) and Wails marshals every binding
 * return value through encoding/json. Unmarshalable fields (channels,
 * *exec.Cmd, *os.File, sync.Once, sync.RWMutex) MUST be tagged `-` or
 * the frontend launches with `FAT | json: unsupported type: func() error`.
 * 
 * Done MUST be closed exactly once via signalDone(); both the reader goroutine
 * (when PTY EOFs) and CloseTerminal race to it, and double-close panics.
 */
export class Terminal {
    "id": string;
    "width": number;
    "height": number;
    "workingDir": string;

    /** Creates a new Terminal instance. */
    constructor($$source: Partial<Terminal> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Terminal instance from a string or object.
     */
    static createFrom($$source: any = {}): Terminal {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Terminal($$parsedSource as Partial<Terminal>);
    }
}

// Private type creation functions
const $$createType0 = CWDSession.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
