// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CWDSession is a single session's last-known CWD.
 */
export interface CWDSession {
    "cwd": string;
    "updatedAt": number;
}

/**
 * CWDStats summarizes per-session CWD-tracking state for the frontend.
 * Mirrors the legacy /api/terminal/cwd/stats response shape so existing
 * clients can adopt the new binding without reshaping.
 */
export interface CWDStats {
    "enabled": boolean;
    "platform": string;
    "sessions": number;
    "resolutions": number;
    "lastResolvedAt": number;
    "strategy": string;
    "perSession": { [_ in string]?: CWDSession } | null;
}

/**
 * Terminal represents a terminal session.
 * 
 * JSON tags are critical: this struct is returned by Wails-bound methods
 * (`CreateTerminal`, `GetTerminalInfo`) and Wails marshals every binding
 * return value through encoding/json. Unmarshalable fields (channels,
 * *exec.Cmd, *os.File, sync.Once, sync.RWMutex) MUST be tagged `-` or
 * the frontend launches with `FAT | json: unsupported type: func() error`.
 * 
 * Done MUST be closed exactly once via signalDone(); both the reader goroutine
 * (when PTY EOFs) and CloseTerminal race to it, and double-close panics.
 */
export interface Terminal {
    "id": string;
    "width": number;
    "height": number;
    "workingDir": string;
}
