// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as os$0 from "../../../../os/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as exec$0 from "../../../../os/exec/models.js";

/**
 * Terminal represents a terminal session
 */
export class Terminal {
    "ID": string;
    "Width": number;
    "Height": number;
    "Command": exec$0.Cmd | null;
    "PTY": os$0.File | null;
    "Output": any;
    "Input": any;
    "Done": any;
    "WorkingDir": string;

    /** Creates a new Terminal instance. */
    constructor($$source: Partial<Terminal> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }
        if (!("Command" in $$source)) {
            this["Command"] = null;
        }
        if (!("PTY" in $$source)) {
            this["PTY"] = null;
        }
        if (!("Output" in $$source)) {
            this["Output"] = null;
        }
        if (!("Input" in $$source)) {
            this["Input"] = null;
        }
        if (!("Done" in $$source)) {
            this["Done"] = null;
        }
        if (!("WorkingDir" in $$source)) {
            this["WorkingDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Terminal instance from a string or object.
     */
    static createFrom($$source: any = {}): Terminal {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Command" in $$parsedSource) {
            $$parsedSource["Command"] = $$createField3_0($$parsedSource["Command"]);
        }
        if ("PTY" in $$parsedSource) {
            $$parsedSource["PTY"] = $$createField4_0($$parsedSource["PTY"]);
        }
        return new Terminal($$parsedSource as Partial<Terminal>);
    }
}

// Private type creation functions
const $$createType0 = exec$0.Cmd.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = os$0.File.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
