<template>
  <span
    class="fi"
    :class="{ 'fi-loading': loadingForFile, 'fi-fallback': !icon && !loadingForFile }"
    :style="iconStyle"
    role="img"
    :aria-label="label"
  >
    <!-- Directory: always show the folder glyph immediately. We don't
         go through the file-icons resolver for directories because the
         result is "no match" 99% of the time anyway, which left dirs
         showing '…' indefinitely while the resolver chewed through
         8000+ regex rules. -->
    <svg
      v-if="isDirectory"
      class="fi-svg"
      viewBox="0 0 16 16"
      preserveAspectRatio="xMidYMid meet"
    >
      <path
        d="M1.5 4.5 a1 1 0 0 1 1-1 H6 l1.5 1.5 H13.5 a1 1 0 0 1 1 1 V12 a1 1 0 0 1 -1 1 H2.5 a1 1 0 0 1 -1 -1 Z"
        fill="currentColor"
      />
    </svg>
    <!-- File path: matched icon → loading dots → extension stamp. -->
    <svg
      v-else-if="icon"
      class="fi-svg"
      :viewBox="`0 0 ${icon.width} ${icon.height}`"
      preserveAspectRatio="xMidYMid meet"
      v-html="icon.svg"
    />
    <span v-else-if="loadingForFile" class="fi-placeholder">…</span>
    <span v-else class="fi-placeholder">{{ fallback }}</span>
  </span>
</template>

<script setup lang="ts">
/**
 * FileIcon — renders an eDEX-UI file-icon SVG for the given filename.
 *
 * Backed by the upstream icon bundle (Atom file-icons + FontAwesome
 * brands + Devopicons + MFixx + Bytesize) shipped at
 * `frontend/app/assets/data/file-icons.json` and matched by the
 * `frontend/app/utils/file-icons-match.js` regex table.
 *
 * The SVG is inlined via v-html — the icon JSON is generated by
 * `file-icons-generator.js` from trusted upstream sources, so XSS is
 * not a concern. Color flows through CSS `color` so the active theme
 * accent shows through.
 *
 * Falls back to a one- or two-letter extension stamp when the matcher
 * has no rule for the file, so cells are never blank.
 */
import { ref, watch, computed } from 'vue'
import { resolveFileIcon, type FileIconRecord } from '~/composables/useFileIcons'

const props = defineProps<{
  /** Full basename or relative path. The matcher is path-aware (e.g.
   *  `node_modules`, `.git`), so passing the relative path improves
   *  accuracy. */
  filename: string
  /** Whether this entry is a directory; affects only the fallback glyph
   *  so dirs don't get an extension stamp. */
  isDirectory?: boolean
  /** Width and height as a CSS length. Defaults to a square sized to
   *  the eDEX grid cell metrics. */
  size?: string
}>()

const icon = ref<FileIconRecord | null>(null)
const loading = ref(false)
// Directories never run the resolver — `loading` only matters for the
// file fallback chain. Computed so the template can reuse it without
// repeating the !isDirectory check.
const loadingForFile = computed(() => loading.value && !props.isDirectory)

const iconStyle = computed(() => {
  const size = props.size ?? '2.6vh'
  return { width: size, height: size }
})

// Files only — directories use a real folder SVG above. The two-letter
// extension stamp is for files without a matching icon rule.
const fallback = computed(() => {
  const dot = props.filename.lastIndexOf('.')
  if (dot < 0 || dot === props.filename.length - 1) return '·'
  return props.filename.slice(dot + 1, dot + 3).toUpperCase()
})

const label = computed(
  () => `${props.isDirectory ? 'Folder' : 'File'} icon for ${props.filename}`,
)

let inflight = 0
async function loadIcon() {
  const stamp = ++inflight
  loading.value = true
  try {
    const rec = await resolveFileIcon(props.filename)
    if (stamp !== inflight) return
    icon.value = rec
  } catch {
    if (stamp === inflight) icon.value = null
  } finally {
    if (stamp === inflight) loading.value = false
  }
}

watch(
  () => props.filename,
  () => {
    icon.value = null
    // Skip the resolver for directories — they always render the
    // generic folder SVG, no per-name lookup needed.
    if (props.filename && !props.isDirectory) loadIcon()
  },
  { immediate: true },
)
</script>

<style scoped>
.fi {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  color: var(--accent);
}

.fi-svg {
  width: 100%;
  height: 100%;
  fill: currentColor;
}

.fi-svg :deep(*) {
  fill: currentColor;
}

.fi-placeholder {
  font-family: var(--font_main);
  font-size: 0.85em;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  opacity: 0.7;
}

.fi-loading .fi-placeholder { opacity: 0.4; }
.fi-fallback .fi-placeholder { opacity: 0.65; }
</style>
