// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EventBus handles event publishing and subscription
 */
export class EventBus {

    /** Creates a new EventBus instance. */
    constructor($$source: Partial<EventBus> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventBus instance from a string or object.
     */
    static createFrom($$source: any = {}): EventBus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EventBus($$parsedSource as Partial<EventBus>);
    }
}
