// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FeatureDetection holds platform feature detection results
 */
export class FeatureDetection {
    "Platform": PlatformInfo;
    "Features": { [_: string]: boolean };

    /** Creates a new FeatureDetection instance. */
    constructor($$source: Partial<FeatureDetection> = {}) {
        if (!("Platform" in $$source)) {
            this["Platform"] = (new PlatformInfo());
        }
        if (!("Features" in $$source)) {
            this["Features"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureDetection instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureDetection {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Platform" in $$parsedSource) {
            $$parsedSource["Platform"] = $$createField0_0($$parsedSource["Platform"]);
        }
        if ("Features" in $$parsedSource) {
            $$parsedSource["Features"] = $$createField1_0($$parsedSource["Features"]);
        }
        return new FeatureDetection($$parsedSource as Partial<FeatureDetection>);
    }
}

/**
 * PlatformInfo holds platform-specific information and capabilities
 */
export class PlatformInfo {
    "OS": string;
    "Arch": string;
    "IsWindows": boolean;
    "IsLinux": boolean;
    "IsDarwin": boolean;
    "IsUnix": boolean;
    "HasPTY": boolean;
    "HasInotify": boolean;
    "HasAudioAPI": boolean;
    "PathSeparator": string;
    "LineEnding": string;
    "ExecutableExt": string;
    "SupportsSymlinks": boolean;

    /** Creates a new PlatformInfo instance. */
    constructor($$source: Partial<PlatformInfo> = {}) {
        if (!("OS" in $$source)) {
            this["OS"] = "";
        }
        if (!("Arch" in $$source)) {
            this["Arch"] = "";
        }
        if (!("IsWindows" in $$source)) {
            this["IsWindows"] = false;
        }
        if (!("IsLinux" in $$source)) {
            this["IsLinux"] = false;
        }
        if (!("IsDarwin" in $$source)) {
            this["IsDarwin"] = false;
        }
        if (!("IsUnix" in $$source)) {
            this["IsUnix"] = false;
        }
        if (!("HasPTY" in $$source)) {
            this["HasPTY"] = false;
        }
        if (!("HasInotify" in $$source)) {
            this["HasInotify"] = false;
        }
        if (!("HasAudioAPI" in $$source)) {
            this["HasAudioAPI"] = false;
        }
        if (!("PathSeparator" in $$source)) {
            this["PathSeparator"] = "";
        }
        if (!("LineEnding" in $$source)) {
            this["LineEnding"] = "";
        }
        if (!("ExecutableExt" in $$source)) {
            this["ExecutableExt"] = "";
        }
        if (!("SupportsSymlinks" in $$source)) {
            this["SupportsSymlinks"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlatformInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PlatformInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlatformInfo($$parsedSource as Partial<PlatformInfo>);
    }
}

// Private type creation functions
const $$createType0 = PlatformInfo.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
