// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FeatureDetection holds platform feature detection results
 */
export interface FeatureDetection {
    "Platform": PlatformInfo;
    "Features": { [_ in string]?: boolean } | null;
}

/**
 * PlatformInfo holds platform-specific information and capabilities
 */
export interface PlatformInfo {
    "OS": string;
    "Arch": string;
    "IsWindows": boolean;
    "IsLinux": boolean;
    "IsDarwin": boolean;
    "IsUnix": boolean;
    "HasPTY": boolean;
    "HasInotify": boolean;
    "HasAudioAPI": boolean;
    "PathSeparator": string;
    "LineEnding": string;
    "ExecutableExt": string;
    "SupportsSymlinks": boolean;
}
