// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearNetworkAlerts() {
  return window['go']['coordinator']['ServiceCoordinator']['ClearNetworkAlerts']();
}

export function CloseTerminal(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['CloseTerminal'](arg1);
}

export function CreateColorScheme(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['CreateColorScheme'](arg1);
}

export function CreateFontConfiguration(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['CreateFontConfiguration'](arg1);
}

export function CreateTerminal(arg1, arg2) {
  return window['go']['coordinator']['ServiceCoordinator']['CreateTerminal'](arg1, arg2);
}

export function DeleteColorScheme(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['DeleteColorScheme'](arg1);
}

export function DeleteFontConfiguration(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['DeleteFontConfiguration'](arg1);
}

export function GetBandwidthData(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['GetBandwidthData'](arg1);
}

export function GetCPUUsage() {
  return window['go']['coordinator']['ServiceCoordinator']['GetCPUUsage']();
}

export function GetColorScheme(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['GetColorScheme'](arg1);
}

export function GetColorSchemeConfig() {
  return window['go']['coordinator']['ServiceCoordinator']['GetColorSchemeConfig']();
}

export function GetColorSchemePreview(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['GetColorSchemePreview'](arg1);
}

export function GetColorSchemes() {
  return window['go']['coordinator']['ServiceCoordinator']['GetColorSchemes']();
}

export function GetDefaultColorScheme() {
  return window['go']['coordinator']['ServiceCoordinator']['GetDefaultColorScheme']();
}

export function GetDefaultFontConfiguration() {
  return window['go']['coordinator']['ServiceCoordinator']['GetDefaultFontConfiguration']();
}

export function GetDiskUsage() {
  return window['go']['coordinator']['ServiceCoordinator']['GetDiskUsage']();
}

export function GetEventBus() {
  return window['go']['coordinator']['ServiceCoordinator']['GetEventBus']();
}

export function GetFontConfiguration(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['GetFontConfiguration'](arg1);
}

export function GetFontConfigurations() {
  return window['go']['coordinator']['ServiceCoordinator']['GetFontConfigurations']();
}

export function GetFontMetrics(arg1, arg2) {
  return window['go']['coordinator']['ServiceCoordinator']['GetFontMetrics'](arg1, arg2);
}

export function GetFontSettings() {
  return window['go']['coordinator']['ServiceCoordinator']['GetFontSettings']();
}

export function GetMemoryUsage() {
  return window['go']['coordinator']['ServiceCoordinator']['GetMemoryUsage']();
}

export function GetMonospaceFonts() {
  return window['go']['coordinator']['ServiceCoordinator']['GetMonospaceFonts']();
}

export function GetNetworkAlerts() {
  return window['go']['coordinator']['ServiceCoordinator']['GetNetworkAlerts']();
}

export function GetNetworkConfig() {
  return window['go']['coordinator']['ServiceCoordinator']['GetNetworkConfig']();
}

export function GetNetworkConnections() {
  return window['go']['coordinator']['ServiceCoordinator']['GetNetworkConnections']();
}

export function GetNetworkInfo() {
  return window['go']['coordinator']['ServiceCoordinator']['GetNetworkInfo']();
}

export function GetNetworkMetrics() {
  return window['go']['coordinator']['ServiceCoordinator']['GetNetworkMetrics']();
}

export function GetNetworkStatistics() {
  return window['go']['coordinator']['ServiceCoordinator']['GetNetworkStatistics']();
}

export function GetPlatform() {
  return window['go']['coordinator']['ServiceCoordinator']['GetPlatform']();
}

export function GetService(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['GetService'](arg1);
}

export function GetSystemFonts() {
  return window['go']['coordinator']['ServiceCoordinator']['GetSystemFonts']();
}

export function GetSystemInfo() {
  return window['go']['coordinator']['ServiceCoordinator']['GetSystemInfo']();
}

export function GetTerminalInfo(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['GetTerminalInfo'](arg1);
}

export function GetTopProcesses(arg1, arg2) {
  return window['go']['coordinator']['ServiceCoordinator']['GetTopProcesses'](arg1, arg2);
}

export function ImportFont(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['ImportFont'](arg1);
}

export function Initialize(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['Initialize'](arg1);
}

export function IsNetworkMonitoring() {
  return window['go']['coordinator']['ServiceCoordinator']['IsNetworkMonitoring']();
}

export function IsStarted() {
  return window['go']['coordinator']['ServiceCoordinator']['IsStarted']();
}

export function ListTerminals() {
  return window['go']['coordinator']['ServiceCoordinator']['ListTerminals']();
}

export function ReadDirectory(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['ReadDirectory'](arg1);
}

export function ResetNetworkService() {
  return window['go']['coordinator']['ServiceCoordinator']['ResetNetworkService']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['coordinator']['ServiceCoordinator']['ResizeTerminal'](arg1, arg2, arg3);
}

export function ResolveNetworkAlert(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['ResolveNetworkAlert'](arg1);
}

export function ScanSystemFonts() {
  return window['go']['coordinator']['ServiceCoordinator']['ScanSystemFonts']();
}

export function SetDefaultColorScheme(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['SetDefaultColorScheme'](arg1);
}

export function SetDefaultFontConfiguration(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['SetDefaultFontConfiguration'](arg1);
}

export function Shutdown() {
  return window['go']['coordinator']['ServiceCoordinator']['Shutdown']();
}

export function StartMonitoring(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['StartMonitoring'](arg1);
}

export function StartNetworkMonitoring() {
  return window['go']['coordinator']['ServiceCoordinator']['StartNetworkMonitoring']();
}

export function StopMonitoring() {
  return window['go']['coordinator']['ServiceCoordinator']['StopMonitoring']();
}

export function StopNetworkMonitoring() {
  return window['go']['coordinator']['ServiceCoordinator']['StopNetworkMonitoring']();
}

export function UpdateColorScheme(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['UpdateColorScheme'](arg1);
}

export function UpdateColorSchemeConfig(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['UpdateColorSchemeConfig'](arg1);
}

export function UpdateFontConfiguration(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['UpdateFontConfiguration'](arg1);
}

export function UpdateFontSettings(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['UpdateFontSettings'](arg1);
}

export function UpdateNetworkConfig(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['UpdateNetworkConfig'](arg1);
}

export function ValidateColorScheme(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['ValidateColorScheme'](arg1);
}

export function ValidateFont(arg1) {
  return window['go']['coordinator']['ServiceCoordinator']['ValidateFont'](arg1);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['coordinator']['ServiceCoordinator']['WriteToTerminal'](arg1, arg2);
}
