// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {terminal} from '../models';
import {events} from '../models';
import {utils} from '../models';
import {context} from '../models';

export function ClearNetworkAlerts():Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateColorScheme(arg1:any):Promise<void>;

export function CreateFontConfiguration(arg1:any):Promise<void>;

export function CreateTerminal(arg1:number,arg2:number):Promise<terminal.Terminal>;

export function DeleteColorScheme(arg1:string):Promise<void>;

export function DeleteFontConfiguration(arg1:string):Promise<void>;

export function GetBandwidthData(arg1:string):Promise<any>;

export function GetCPUUsage():Promise<any>;

export function GetColorScheme(arg1:string):Promise<any>;

export function GetColorSchemeConfig():Promise<any>;

export function GetColorSchemePreview(arg1:string):Promise<any>;

export function GetColorSchemes():Promise<Record<string, any>>;

export function GetDefaultColorScheme():Promise<any>;

export function GetDefaultFontConfiguration():Promise<any>;

export function GetDiskUsage():Promise<any>;

export function GetEventBus():Promise<events.EventBus>;

export function GetFontConfiguration(arg1:string):Promise<any>;

export function GetFontConfigurations():Promise<Record<string, any>>;

export function GetFontMetrics(arg1:string,arg2:number):Promise<any>;

export function GetFontSettings():Promise<any>;

export function GetMemoryUsage():Promise<any>;

export function GetMonospaceFonts():Promise<Array<any>>;

export function GetNetworkAlerts():Promise<any>;

export function GetNetworkConfig():Promise<any>;

export function GetNetworkConnections():Promise<any>;

export function GetNetworkInfo():Promise<any>;

export function GetNetworkMetrics():Promise<any>;

export function GetNetworkStatistics():Promise<any>;

export function GetPlatform():Promise<utils.FeatureDetection>;

export function GetService(arg1:string):Promise<any>;

export function GetSystemFonts():Promise<Record<string, any>>;

export function GetSystemInfo():Promise<any>;

export function GetTerminalInfo(arg1:string):Promise<terminal.Terminal>;

export function GetTopProcesses(arg1:string,arg2:number):Promise<any>;

export function ImportFont(arg1:any):Promise<any>;

export function Initialize(arg1:context.Context):Promise<void>;

export function IsNetworkMonitoring():Promise<boolean>;

export function IsStarted():Promise<boolean>;

export function ListTerminals():Promise<Array<string>>;

export function ReadDirectory(arg1:string):Promise<any>;

export function ResetNetworkService():Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveNetworkAlert(arg1:string):Promise<void>;

export function ScanSystemFonts():Promise<void>;

export function SetDefaultColorScheme(arg1:string):Promise<void>;

export function SetDefaultFontConfiguration(arg1:string):Promise<void>;

export function Shutdown():Promise<void>;

export function StartMonitoring(arg1:context.Context):Promise<void>;

export function StartNetworkMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;

export function StopNetworkMonitoring():Promise<void>;

export function UpdateColorScheme(arg1:any):Promise<void>;

export function UpdateColorSchemeConfig(arg1:any):Promise<void>;

export function UpdateFontConfiguration(arg1:any):Promise<void>;

export function UpdateFontSettings(arg1:any):Promise<void>;

export function UpdateNetworkConfig(arg1:any):Promise<void>;

export function ValidateColorScheme(arg1:any):Promise<any>;

export function ValidateFont(arg1:any):Promise<any>;

export function WriteToTerminal(arg1:string,arg2:Array<number>):Promise<void>;
